### ISSUE TITLE
Resharper 9

### ISSUE THREAD

**Issue by denxorz** [hhariri/CleanCode#10]
I upgraded from Resharper 8 to Resharper 9. Sadly enough I can no longer use this plugin. 

Is it possible to make this plugin available for Resharper 9?

Current dependencies of the plugin (based on this page https://resharper-plugins.jetbrains.com/packages/CleanCode/):
ReSharper (≥ 8.2 && < 8.3)

**Comment by hhariri** [comment]
pinging @citizenmatt as he's working on upgrading these plugins.

**Comment by citizenmatt** [comment]
Closing this as obsolete.
