### ISSUE TITLE
Resharper 10

### ISSUE THREAD

**Issue by SalamiArmy** [hhariri/CleanCode#11]
I upgraded from Resharper 9 to Resharper 10. Sadly enough I can no longer use this plugin.

Is it possible to make this plugin available for Resharper 10?

Current dependencies of the plugin (based on this page https://resharper-plugins.jetbrains.com/packages/CleanCode/):
ReSharper (≥ 8.2 && < 8.3)

**Comment by citizenmatt** [comment]
Closing this as obsolete.

**Comment by SalamiArmy** [comment]
Resharper 10 is obsolete or the plugin is?

**Comment by citizenmatt** [comment]
ReSharper 10 support. I'm working on 2016.2 support instead.
