### ISSUE TITLE
Incorrectly reports a method being too long

### ISSUE THREAD

**Issue by DavidArno** [hhariri/CleanCode#12]
For example, the following method is reported as being too long:
````csharp
public static Func<T2, TResult> Apply<T1, T2, TResult>(this Func<T1, T2, TResult> functionToApply, T1 p1) => 
    p2 => functionToApply(p1, p2);
````
Regardless of what value I set "Maximum statements per method" to (tried 9999).

**Comment by citizenmatt** [comment]
Ah. It's looking at the number of declarations - you can bump that up as a workaround for now.

I've merged two checks - one was counting the number of statements in a method, the other was counting the number of declarations. There is a third check counting the number of parameters in a method, so I assumed the one counting the number of declarations was looking at how many variables you were creating. A reasonable metric for the size and complexity of a method.

However, a method declaration's children in the AST include parameter and type parameter declarations. So, it's counted the generic parameters and all of the method argument parameters and taken those as a metric for the number of variable declarations. I need to be looking at the number of declarations in the method body. I'll get it updated. Thanks for the bug report!

**Comment by DavidArno** [comment]
> Ah. It's looking at the number of declarations - you can bump that up as a workaround for now.
Yep, that works as a workaround. Thanks.
