### ISSUE TITLE
ReSharper 2016.2 support

### ISSUE THREAD

**Issue by Craigfis** [hhariri/CleanCode#14]
Any ETA for support for this version?

**Comment by citizenmatt** [comment]
It's already there! Go to Extension Manager and search for it.

**Comment by Craigfis** [comment]
Ahh, it wasn't showing for me on RS2016.1, After upgrading to 2016.2 and restarting VS, I now see it.
However, according to this page the last release was in 2014: https://resharper-plugins.jetbrains.com/packages/CleanCode/
Ahh, I see, you changed the package name. Why?

**Comment by citizenmatt** [comment]
The name change is a requirement of the installer since ReSharper 9, I think it was. It needs to be at least a two part name. Annoying, but there you are.
