### ISSUE TITLE
"expression body" methods are allways too long

### ISSUE THREAD

**Issue by egreiner** [hhariri/CleanCode#18]
expression body:
public static T GetInstanceAll<T>() where T: ICanFilter<T>, new() 
            => GetInstance<T>(Filter.Default.FilterAllId, Filter.Default.FilterAll);
-> Methode too long

the same as statement body is OK:
        public static T GetInstanceAll<T>() where T: ICanFilter<T>, new()
        {
            return GetInstance<T>(Filter.Default.FilterAllId, Filter.Default.FilterAll);
        }

**Comment by citizenmatt** [comment]
Can you make sure you're running the latest version, please? I can't repro in 5.0.2 (and I've just pushed 5.0.3 for #19, too - give that a go).

**Comment by egreiner** [comment]
Installed it yesterday (found project on twitter :) ) so should be 5.0.2.
btw where can i see the version nr? in the extension manager i can only see the update to 5.0.3 but not the installed version...

**Comment by citizenmatt** [comment]
If you hover over the "more info" link, you'll see the currently installed version.
