### ISSUE TITLE
Ability to suppress warnings through normal ReSharper method.

### ISSUE THREAD

**Issue by wiredwiz** [hhariri/CleanCode#21]
It would be good if the warnings that were generated could also be suppressed via comments/attributes as per the usual way in ReSharper.  I have unit test classes that often violate many of the rules and It would be preferable to to ignore the rules for those specific classes.

**Comment by citizenmatt** [comment]
The current works with ReSharper's suppression comments. Could you check your running 5.0.3 of the plugin? Please reopen if it's still failing with the latest version.

**Comment by wiredwiz** [comment]
Thanks, I think there must be something going on with my install of ReSharper.  This is the second extension I have had issues with warnings persisting even after I have added suppression comments, only to find a day later these have suddenly cleared up.

**Comment by citizenmatt** [comment]
It's possibly worth cleaning caches and restarting Visual Studio (ReSharper &rarr; Options &rarr; General &rarr; Clean caches). This should get rid of any lingering things like this. If it reoccurs, report a bug at https://youtrack.jetbrains.com

**Comment by wiredwiz** [comment]
Thank you, I appreciate that recommendation, I did not even know about that option.
