### ISSUE TITLE
CleanCode For Visual Studio 2019

### ISSUE THREAD

**Issue by AnHuynh89** [hhariri/CleanCode#39]
Hi 

I installed Visual studio 2019 and Resharper 2019.1 but I don't find cleancode Plugin. 

Any update for Resharper 2019? 

Thanks

**Comment by MO2k4** [comment]
There will be a new version out there in a few days. => [Link](https://plugins.jetbrains.com/plugin/11677-clean-code)

**Comment by AnHuynh89** [comment]
Thanks @MO2k4

**Comment by MO2k4** [comment]
The new version is now availabe :-)

https://plugins.jetbrains.com/plugin/11677-clean-code/update/62109

**Comment by SuperJMN** [comment]
Thanks, man!
