### ISSUE TITLE
Restart Development

### ISSUE THREAD

**Issue by chris-schuetz** [hhariri/CleanCode#40]
I would love to use this extension and contribute to further development of it. Is there a chance to get the current maintainer interested in further development or change the maintainer to someone interested in bringing this extension to the current Resharper version?

**Comment by MO2k4** [comment]
Hey Chris,

there is active development in this fork => https://github.com/MO2k4/CleanCode

now it also supports vb.net and Jetbrains Rider :-)

i will make a new release today to support 2019.2.3

**Comment by chris-schuetz** [comment]
Looks good.
